runtime: nodejs20
env: standard
entrypoint: npm start

env_variables:
  NODE_ENV: production
  NPM_CONFIG_PRODUCTION: true

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 2

service_account: github-service@irwebsite-444921.iam.gserviceaccount.com
